#!/bin/bash
#----------------------------------------------------
# Example SLURM job script to run OpenMP applications
# on TACC's Stampede system.
#----------------------------------------------------
#SBATCH -J openmp_job       # Job name
#SBATCH -o openmp_job.o%j   # Name of stdout output file(%j expands to jobId)
#SBATCH -e openmp_job.o%j   # Name of stderr output file(%j expands to jobId)
#SBATCH -p normal           # Submit to the 'normal' or 'development' queue
#SBATCH -N 4                # Total number of nodes requested (16 cores/node)
#SBATCH -n 32              # Total number of mpi tasks requested
#SBATCH -t 24:00:00         # Run time (hh:mm:ss) - 1.5 hours

#SBATCH --mail-user=janaki.vamaraju@gmail.com
#SBATCH --mail-type=ALL
#SBATCH --mail-type=begin
#SBATCH --mail-type=end

#SBATCH -A A-igam       # class project/account code;
                          # necessary if you have multiple project accounts



# This example will run an OpenMP application using 16 threads

# Set the number of threads per task(Default=1)

export OMP_NUM_THREADS=32
make
# Run the OpenMP application
./forward.out 
